# Change these first
owner: h3ct0rjs # Your GitHub organization or username, where this repository lives
repo: www-status-site # The name of this repository

sites:
  - name: DevOps Colombia
    url: https://devops.com.co
  - name: PereiraTechTalks
    url: https://pereiratechtalks.com

# status-website:
#   # Add your custom domain name, or remove the `cname` line if you don't have a domain
#   # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#   cname: demo.upptime.js.org
#   # baseUrl: /your-repo-name
#   logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
#   name: DevOps Colombia
#   introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
#   introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
#   navbar:
#     - title: Status
#       href: /
#     - title: GitHub
#       href: https://github.com/$OWNER/$REPO


assignees:
  - h3ct0rjs
skipDeleteIssues: true
status-website:
  theme: night
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Monitoring my personal website devops.com.co
  robotsText: "User-agent: * \n Disallow: /"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

user-agent: h3ct0rjs
